### ISSUE TITLE
latest patch might've broken this

### ISSUE THREAD

**Issue by Sondash300** [c0dycode/BL3HotfixWebUI#14]
i followed the installation instructions exactly and i'm using the latest version of both this and the injector. it was working perfectly fine yesterday but stopped working today. i know there was a hotfix that started a new community challenge and ended the Traunt raid boss event yesterday. is there a possibility that they might've broken modding either on purpose or on accident?

**Comment by c0dycode** [comment]
Everything's still working fine for me.
Do you get any errors in the log?

![image](https://user-images.githubusercontent.com/3851319/140580198-fae77afd-de42-461e-b8e2-887daa42cfa6.png)

**Comment by Sondash300** [comment]
[log.log](https://github.com/c0dycode/BL3HotfixWebUI/files/7489011/log.log)
here's my log. what's odd, i don't see any errors and it says it's launching fine. yet when i get in game, none of my mods work at all

**Comment by Sondash300** [comment]
okay, i tried launching the game and the hotfix merger isn't finding the borderlands 3 process. it just says waiting for borderlands3.exe and doesn't go past that

**Comment by c0dycode** [comment]
That's odd.
Try removing the B3HM.dll and manually launch the B3HM.exe instead, for testing.

Do you use any antivirus software that might have gotten an update and could now silently prevent this from working properly?

**Comment by Sondash300** [comment]
checked antivirus and there wasn't anything there involving this program. tried removing the DLL like you suggested and same result

**Comment by c0dycode** [comment]
Hm, I assume you did reboot your pc since then?

The only thing that happens in code is basically this
```go
bl3logger.Println(websockethelper.LogInfo, "Waiting for Borderlands3.exe...")
id := 0
for {
	proc := processhelper.FindProcessWithPath("Borderlands3.exe", "OakGame\\Binaries\\Win64")
	if proc.ProcessID != 0 {
		id = proc.ProcessID
	}
	if id != 0 {
		.... 
	}
	time.Sleep(25 * time.Millisecond)
}
```

So, it prints the message you see in the log and then attempts to find a process called "Borderlands3.exe" where the path contains the location "OakGame\Binaries\Win64". This is a check because the Epic Games version is dumb and launches two "Borderlands3.exe"-processes.

It'll retry to do this every 25ms - indefinitely. Unless there's an error, then B3HM will close itself.
Since you can manually close B3HM via the systray two minutes later, that means that there is no actual error and it has had more than enough time to retry over and over again.

You can try and see if it actually keeps searching for that process by using B3HM.exe and keep looking at it in your Task-Manager.

If it's sitting at 0 ~ 0,3% CPU usage, then it's stuck somewhere.

If it's actively checking for that process to exist, then it should be closer to or above 1% CPU usage.

Unfortunately neither of those will really help with figuring out what the actual issue might be though.

**Comment by Sondash300** [comment]
okay. deleting the DLL and then rebooting fixed it. thanks for the help. your modding tool has become borderline necessary for some of the problems this game has

**Comment by c0dycode** [comment]
Glad it's working again!

And happy to hear you get use out of this tool :)
